# Generated by Django 6.0.6 on 2026-06-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_listing_express_buyout_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Номер заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('purpose', models.CharField(choices=[('listing_vip', 'VIP-листинг'), ('listing_unlock', 'Разблокировка листинга'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Назначение платежа')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Выполнен'), ('failed', 'Отклонён'), ('reversed', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('liqpay_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа LiqPay')),
                ('liqpay_status', models.CharField(blank=True, max_length=50, verbose_name='Статус LiqPay')),
                ('liqpay_raw', models.JSONField(blank=True, null=True, verbose_name='Сырой ответ LiqPay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='listings.listing', verbose_name='Листинг')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
