# Generated by Django 6.0.6 on 2026-07-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_listings', '0003_lifecycle_and_promotion'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='local_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='local_listings.locallisting', verbose_name='Місцеве оголошення'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='local_listings.promotiontariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('listing_vip', 'VIP-листинг'), ('listing_unlock', 'Разблокировка листинга'), ('local_listing_promote', 'Просування оголошення'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='Назначение платежа'),
        ),
    ]
