# Generated by Django 6.0.6 on 2026-06-17 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('service', 'СТО'), ('painter', 'Маляр/кузовщик'), ('parts', 'Запчасти'), ('other', 'Другое')], default='service', max_length=10, verbose_name='Тип')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_shops', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проверенный партнёр',
                'verbose_name_plural': 'Проверенные партнёры',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
