# Generated by Django 6.0.6 on 2026-06-20 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trustedshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Контактный телефон')),
                ('documents', models.URLField(blank=True, verbose_name='Ссылка на документы')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('review_notes', models.TextField(blank=True, verbose_name='Заметки рассмотрения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка дилера',
                'verbose_name_plural': 'Заявки дилеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
