# Generated by Django 6.0.6 on 2026-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата згоди з умовами'),
        ),
    ]
