# Generated by Django 6.0.6 on 2026-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_banned_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerapplication',
            name='agreed_to_processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата згоди на обробку даних'),
        ),
    ]
