# Generated by Django 6.0.6 on 2026-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionFeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('auction', models.CharField(choices=[('copart', 'Copart'), ('iaai', 'IAAI')], max_length=10, verbose_name='Аукцион')),
                ('min_price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от ($)')),
                ('max_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до ($, пусто=без лимита)')),
                ('fee_fixed_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Фиксированный сбор ($)')),
                ('fee_pct', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='% от цены (напр. 0.1000 = 10%)')),
            ],
            options={
                'verbose_name': 'Тариф аукционного сбора',
                'verbose_name_plural': 'Тарифы аукционных сборов',
                'ordering': ['auction', 'min_price_usd'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs_snapshot', models.JSONField(verbose_name='Снимок входных данных')),
                ('rates_snapshot', models.JSONField(verbose_name='Снимок применённых ставок')),
                ('breakdown', models.JSONField(verbose_name='Детализация расчёта')),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого USD')),
                ('total_uah', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итого UAH')),
                ('is_estimate', models.BooleanField(default=True, verbose_name='Ориентировочный расчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расчёт стоимости',
                'verbose_name_plural': 'Расчёты стоимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomsExciseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], max_length=10, verbose_name='Тип топлива')),
                ('eur_per_100cc', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='EUR за каждые 100 см³')),
                ('age_0_1_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коэфф. 0–1 год')),
                ('age_1_3_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коэфф. 1–3 года')),
                ('age_3_5_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коэфф. 3–5 лет')),
                ('age_5_7_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коэфф. 5–7 лет')),
                ('age_7_plus_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коэфф. 7+ лет')),
                ('duty_rate', models.DecimalField(decimal_places=4, default='0.1000', max_digits=5, verbose_name='Ставка пошлины (10%=0.1000)')),
                ('vat_rate', models.DecimalField(decimal_places=4, default='0.2000', max_digits=5, verbose_name='НДС (20%=0.2000)')),
            ],
            options={
                'verbose_name': 'Ставка акциза/пошлины',
                'verbose_name_plural': 'Ставки акциза/пошлины',
            },
        ),
        migrations.CreateModel(
            name='EuToUaDeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('eu_port', models.CharField(choices=[('klaipeda', 'Клайпеда'), ('gdansk', 'Гданьск')], max_length=20, verbose_name='Порт ЕС')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость ($)')),
            ],
            options={
                'verbose_name': 'Доставка ЕС → Украина',
                'verbose_name_plural': 'Доставка ЕС → Украина',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='Из валюты')),
                ('to_currency', models.CharField(max_length=3, verbose_name='В валюту')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Курс')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OceanFreightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('us_port', models.CharField(max_length=50, verbose_name='Порт США')),
                ('eu_port', models.CharField(choices=[('klaipeda', 'Клайпеда'), ('gdansk', 'Гданьск')], max_length=20, verbose_name='Порт ЕС')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость ($)')),
            ],
            options={
                'verbose_name': 'Морской фрахт',
                'verbose_name_plural': 'Морской фрахт',
            },
        ),
        migrations.CreateModel(
            name='PensionFundBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('min_value_uah', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Стоимость от (грн)')),
                ('max_value_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость до (грн, пусто=без лимита)')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Ставка пенсионного сбора')),
            ],
            options={
                'verbose_name': 'Брекет пенсионного сбора',
                'verbose_name_plural': 'Брекеты пенсионного сбора',
                'ordering': ['min_value_uah'],
            },
        ),
        migrations.CreateModel(
            name='UsLandRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('auction_location', models.CharField(max_length=100, verbose_name='Локация аукциона')),
                ('us_port', models.CharField(max_length=50, verbose_name='Порт США')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость ($)')),
            ],
            options={
                'verbose_name': 'Сухопутная логистика США',
                'verbose_name_plural': 'Сухопутная логистика США',
            },
        ),
    ]
