# Generated by Django 6.0.6 on 2026-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsexciserate',
            name='age_0_1_coeff',
        ),
        migrations.RemoveField(
            model_name='customsexciserate',
            name='age_1_3_coeff',
        ),
        migrations.RemoveField(
            model_name='customsexciserate',
            name='age_3_5_coeff',
        ),
        migrations.RemoveField(
            model_name='customsexciserate',
            name='age_5_7_coeff',
        ),
        migrations.RemoveField(
            model_name='customsexciserate',
            name='age_7_plus_coeff',
        ),
        migrations.AddField(
            model_name='customsexciserate',
            name='engine_cc_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём до (см³, пусто=без лимита)'),
        ),
        migrations.AddField(
            model_name='customsexciserate',
            name='engine_cc_min',
            field=models.IntegerField(default=0, verbose_name='Объём от (см³)'),
        ),
        migrations.AddField(
            model_name='customsexciserate',
            name='ev_excise_eur_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, default='1.0000', max_digits=8, null=True, verbose_name='EUR за кВт·ч (EV/PHEV, null=не применяется)'),
        ),
        migrations.AlterField(
            model_name='customsexciserate',
            name='eur_per_100cc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='EUR за каждые 100 см³ (ДВС)'),
        ),
        migrations.AlterField(
            model_name='customsexciserate',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид (HEV)'), ('phev', 'Гибрид (PHEV, plug-in)')], max_length=10, verbose_name='Тип топлива'),
        ),
    ]
