# Generated by Django 6.0.6 on 2026-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('EUR', 'EUR')], default='USD', max_length=3, verbose_name='Валюта')),
                ('channel', models.CharField(choices=[('retail', 'Розница'), ('wholesale', 'Опт')], default='retail', max_length=10, verbose_name='Канал')),
                ('status', models.CharField(choices=[('in_transit', 'В пути'), ('in_stock', 'В наличии'), ('sold', 'Продан')], default='in_transit', max_length=15, verbose_name='Статус')),
                ('repair_description', models.TextField(blank=True, verbose_name='Описание ремонта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
