# Generated by Django 6.0.6 on 2026-06-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='pricing.calculation', verbose_name='Расчёт стоимости'),
        ),
    ]
