# Generated by Django 6.0.6 on 2026-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='express_buyout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срочный выкуп до'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_express_buyout',
            field=models.BooleanField(default=False, verbose_name='Срочный выкуп'),
        ),
    ]
