# Generated by Django 6.0.6 on 2026-06-23 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_express_buyout_until_and_more'),
        ('pricing', '0004_auction_fee_v2'),
        ('vehicles', '0003_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['channel'], name='listing_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['channel', 'status'], name='listing_channel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listing_price_idx'),
        ),
    ]
