# Generated by Django 6.0.6 on 2026-09-10 10:49
import logging

from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)

VALID_STATUS = ['in_transit', 'in_stock', 'sold']
VALID_CHANNEL = ['retail', 'wholesale']
VALID_CURRENCY = ['USD', 'UAH', 'EUR']

# Значения, которые уже встречались в базе, и то, чем их заменить.
# 'active' семантически ближе всего к 'in_stock': объявление показывалось
# в каталоге как доступное.
STATUS_REMAP = {'active': 'in_stock'}


def normalize(apps, schema_editor):
    """
    Приводит записи в соответствие с choices до наложения ограничения.

    Без этого шага AddConstraint упадёт на существующих данных: в базе
    лежал status='active', которого нет среди вариантов.
    """
    Listing = apps.get_model('listings', 'Listing')

    for bad, good in STATUS_REMAP.items():
        count = Listing.objects.filter(status=bad).update(status=good)
        if count:
            logger.warning('listings: status %r -> %r, записей: %d', bad, good, count)

    # Всё остальное неизвестное — в дефолт модели, иначе миграция не пройдёт.
    rest = Listing.objects.exclude(status__in=VALID_STATUS).update(status='in_transit')
    if rest:
        logger.warning('listings: неизвестный status -> in_transit, записей: %d', rest)

    ch = Listing.objects.exclude(channel__in=VALID_CHANNEL).update(channel='retail')
    if ch:
        logger.warning('listings: неизвестный channel -> retail, записей: %d', ch)

    cur = Listing.objects.exclude(currency__in=VALID_CURRENCY).update(currency='USD')
    if cur:
        logger.warning('listings: неизвестная currency -> USD, записей: %d', cur)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_perf_indexes'),
        ('pricing', '0004_auction_fee_v2'),
        ('vehicles', '0003_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Порядок важен: сначала чистим данные, потом накладываем ограничение.
        migrations.RunPython(normalize, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_transit', 'in_stock', 'sold'])), name='listing_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['retail', 'wholesale'])), name='listing_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'UAH', 'EUR'])), name='listing_currency_valid'),
        ),
    ]
