# Generated by Django 6.0.6 on 2026-06-17 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(max_length=20, unique=True, verbose_name='Номер контейнера')),
                ('vessel', models.CharField(blank=True, max_length=100, verbose_name='Судно')),
                ('us_warehouse', models.CharField(blank=True, max_length=100, verbose_name='Склад США')),
                ('departure_port_us', models.CharField(blank=True, max_length=50, verbose_name='Порт отправки (США)')),
                ('arrival_port_eu', models.CharField(choices=[('klaipeda', 'Клайпеда'), ('gdansk', 'Гданьск')], default='klaipeda', max_length=20, verbose_name='Порт прибытия (ЕС)')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата прибытия')),
                ('status', models.CharField(choices=[('at_us_warehouse', 'На складе в США'), ('loading', 'Погрузка'), ('in_ocean', 'В море'), ('at_eu_port', 'В порту ЕС'), ('on_truck_to_ua', 'Автовоз → Украина'), ('cleared', 'Растаможен'), ('delivered', 'Доставлен')], default='at_us_warehouse', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='shipments', to='vehicles.vehicle', verbose_name='Автомобили')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Отслеживают')),
            ],
            options={
                'verbose_name': 'Контейнер/Шипмент',
                'verbose_name_plural': 'Контейнеры/Шипменты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('at_us_warehouse', 'На складе в США'), ('loading', 'Погрузка'), ('in_ocean', 'В море'), ('at_eu_port', 'В порту ЕС'), ('on_truck_to_ua', 'Автовоз → Украина'), ('cleared', 'Растаможен'), ('delivered', 'Доставлен')], max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tracking_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Событие трекинга',
                'verbose_name_plural': 'События трекинга',
                'ordering': ['created_at'],
            },
        ),
    ]
