# Generated by Django 6.0.6 on 2026-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Марка и модель авто')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN код')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('price_in_usa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на аукционе ($)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена под ключ в Украине ($)')),
                ('status', models.CharField(choices=[('IN_USA', 'На аукционе в США'), ('IN_TRANSIT', 'Плывет в Украину'), ('IN_UKRAINE', 'В Украине / На ремонте / Готов')], default='IN_USA', max_length=20, verbose_name='Статус доставки')),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лота Copart/IAAI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ремонта или состояния')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_photos/')),
            ],
        ),
    ]
