# Generated by Django 6.0.6 on 2026-07-01 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Область')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік')),
                ('mileage_km', models.PositiveIntegerField(verbose_name='Пробіг, км')),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True, verbose_name="Об'єм двигуна, куб.см")),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид'), ('gas', 'Газ')], max_length=20, verbose_name='Тип палива')),
                ('transmission', models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механіка'), ('cvt', 'Варіатор'), ('robot', 'Робот')], max_length=20, verbose_name='КПП')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Позашляховик'), ('hatchback', 'Хетчбек'), ('wagon', 'Універсал'), ('coupe', 'Купе'), ('minivan', 'Мінівен'), ('pickup', 'Пікап'), ('convertible', 'Кабріолет'), ('other', 'Інше')], max_length=20, verbose_name='Тип кузова')),
                ('condition', models.CharField(choices=[('new', 'Новий'), ('used', 'Вживаний'), ('damaged', 'Пошкоджений')], default='used', max_length=20, verbose_name='Стан')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3, verbose_name='Валюта')),
                ('price_type', models.CharField(choices=[('fixed', 'Фіксована'), ('negotiable', 'Торг')], default='fixed', max_length=20, verbose_name='Тип ціни')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активне'), ('pending', 'На модерації'), ('rejected', 'Відхилено'), ('expired', 'Закінчилося'), ('sold', 'Продано'), ('hidden', 'Приховане')], default='draft', max_length=20, verbose_name='Статус')),
                ('seller_type', models.CharField(choices=[('private', 'Приватна особа'), ('dealer', 'Дилер')], default='private', max_length=20, verbose_name='Тип продавця')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='local_listings.city', verbose_name='Місто')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_listings', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='local_listings.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Місцеве оголошення',
                'verbose_name_plural': 'Місцеві оголошення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='local_listings/', verbose_name='Фото')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='URL фото')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='local_listings.locallisting', verbose_name='Оголошення')),
            ],
            options={
                'verbose_name': 'Фото оголошення',
                'verbose_name_plural': 'Фото оголошень',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='local_listings.region', verbose_name='Область'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['status'], name='ll_status_idx'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['make'], name='ll_make_idx'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['year'], name='ll_year_idx'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['price'], name='ll_price_idx'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['region'], name='ll_region_idx'),
        ),
        migrations.AddIndex(
            model_name='locallisting',
            index=models.Index(fields=['fuel_type'], name='ll_fuel_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'slug')},
        ),
    ]
