# Generated by Django 6.0.6 on 2026-07-01 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLocalListingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Оголошення на модерації',
                'verbose_name_plural': 'Черга модерації',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('local_listings.locallisting',),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='agreed_to_rules',
            field=models.BooleanField(default=False, verbose_name='Погодився з правилами'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='agreed_to_rules_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата згоди'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерації'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_local_listings', to=settings.AUTH_USER_MODEL, verbose_name='Перевірив'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина відхилення'),
        ),
    ]
