# Generated by Django 6.0.6 on 2026-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_listings', '0002_moderation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('type', models.CharField(choices=[('renew', 'Продовження'), ('bump', 'Підняти'), ('top', 'ТОП')], max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Днів дії')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тариф просування',
                'verbose_name_plural': 'Тарифи просування',
                'ordering': ['type', 'price'],
            },
        ),
        migrations.AddField(
            model_name='locallisting',
            name='bumped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Піднято'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дійсне до'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='expiry_warned',
            field=models.BooleanField(default=False, verbose_name='Попередження надіслано'),
        ),
        migrations.AddField(
            model_name='locallisting',
            name='promoted_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ТОП до'),
        ),
    ]
