# Generated by Django 6.0.6 on 2026-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('provider', models.CharField(max_length=50, verbose_name='Провайдер')),
                ('report_data', models.JSONField(verbose_name='Данные отчёта')),
                ('demo', models.BooleanField(default=False, verbose_name='Демо-данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VIN-отчёт',
                'verbose_name_plural': 'VIN-отчёты',
                'ordering': ['-created_at'],
                'unique_together': {('vin', 'provider')},
            },
        ),
    ]
