# Generated by Django 6.0.6 on 2026-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleimage_source_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['fuel_type'], name='vehicle_fuel_type_idx'),
        ),
    ]
